Problem set 1: Data importing and cleaning

Due: 11:59pm on Friday, September 8 by uploading to github

Your name:

1. Data importing: "data_finance.csv" contains a dataset with information about sales transactions. Write the appropriate code for each of the tasks below. This section should be completed without generative AI, but with open access to static online resources like course material, stackoverflow, blogs with sample code, etc.

In [66]:
# Load the pandas library
import pandas as pd
import os 

# Import the CSV file 'data_finance.csv' into a DataFrame
current_directory =os.getcwd()
print(f"current directory is {current_directory}")
data= pd.read_csv(f"{current_directory}/raw/data_finance.csv")
#data= pd.read_csv("/Users/chenhanlin/Documents/vandy 23 fall/DS 5610 EDA/Assignment/data/raw/data_finance.csv")

# Display the column names
print(data.head)

# Identify the data types of each column
print(data.dtypes)

# Display the first 5 rows of the DataFrame
print(data.loc[:4,:])

# Display the last 5 rows of the DataFrame
print(data.tail(5))

# Display a random sample of 5 rows
print(data.sample(n=5))

# Calculate the total number of rows and columns in the DataFrame
print(data.shape)

# Display summary statistics for the quantity and price columns
print(data[['quantity','price']].describe())

current directory is /Users/chenhanlin/Documents/vandy 23 fall/DS 5610 EDA/Assignment/data
<bound method NDFrame.head of     transaction_id          product_name  quantity  price
0                1                 Apple         7  12.34
1                2                Banana         2  19.05
2                3                Cherry         9   5.81
3                4                  Date         4   1.76
4                5            Elderberry         8  10.45
5                6                   Fig         3  18.22
6                7                 Grape         1   7.09
7                8              Honeydew         5  23.48
8                9             Jackfruit        10   2.56
9               10                  Kiwi         6   9.71
10              11                 Lemon         7   4.23
11              12                 Mango         3  14.12
12              13             Nectarine         2   6.87
13              14                Orange         6   3.14
14              15                Papaya         9  22.77
15              16                Quince         8   8.65
16              17             Raspberry         4  16.98
17              18            Strawberry         1   0.99
18              19                Tomato         5  11.11
19              20            Ugli fruit        10  20.43
20              21          Vanilla bean         9  17.29
21              22            Watermelon         8  13.67
22              23                 Xigua         3  21.89
23              24  Yellow passion fruit         2  15.54
24              25              Zucchini         6  24.72>
transaction_id      int64
product_name       object
quantity            int64
price             float64
dtype: object
   transaction_id product_name  quantity  price
0               1        Apple         7  12.34
1               2       Banana         2  19.05
2               3       Cherry         9   5.81
3               4         Date         4   1.76
4               5   Elderberry         8  10.45
    transaction_id          product_name  quantity  price
20              21          Vanilla bean         9  17.29
21              22            Watermelon         8  13.67
22              23                 Xigua         3  21.89
23              24  Yellow passion fruit         2  15.54
24              25              Zucchini         6  24.72
    transaction_id product_name  quantity  price
3                4         Date         4   1.76
17              18   Strawberry         1   0.99
24              25     Zucchini         6  24.72
15              16       Quince         8   8.65
13              14       Orange         6   3.14
(25, 4)
        quantity      price
count  25.000000  25.000000
mean    5.520000  12.514800
std     2.902872   7.346783
min     1.000000   0.990000
25%     3.000000   6.870000
50%     6.000000  12.340000
75%     8.000000  18.220000
max    10.000000  24.720000

2. Generative AI comparison. Use a reliable generative AI like ChatGPT, Claude, Bing, Jupyter AI, etc. to answer the same questions as Section 1. You should alter the prompt given to the AI to maximize the accuracy and efficiency of its output. Paste both your prompt and the generative AI's output below.

In [67]:
# Prompt: You are a pandas expert. Help me write these codes: Import the CSV file 'data_finance.csv' into a DataFrame; Display the column names;Identify the data types of each column; Display the first 5 rows of the DataFrame; Display the last 5 rows of the DataFrame; Display a random sample of 5 rows; Calculate the total number of rows and columns in the DataFrame; Display summary statistics for the quantity and price columns;

# AI generated code
# Load Pandas and import the CSV file 'data_finance.csv' into a DataFrame
import pandas as pd
data = pd.read_csv('/mnt/data/data_finance.csv')

# Display the column names
print(data.columns)

# Identify the data types of each column
print(data.dtypes)

# Display the first 5 rows of the DataFrame
print(data.head())

#Display the last 5 rows of the DataFrame:
print(data.tail())

#Display a random sample of 5 rows:
print(data.sample(5))

#Calculate the total number of rows and columns in the DataFrame:
num_rows, num_columns = data.shape
print(f'Total Rows: {num_rows}')
print(f'Total Columns: {num_columns}')

#Display summary statistics for the quantity and price columns:
print(data[['quantity', 'price']].describe())

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data/data_finance.csv'

3. Data cleaning: "data_students.tsv" contains a dataset with information about students. Write the appropriate code for each of the tasks below. This section should be completed without generative AI, but with open access to static online resources like course material, stackoverflow, blogs with sample code, etc.

In [68]:
# Import "data_students.tsv" into a dataframe
import pandas as pd
current_directory =os.getcwd()
print(f"current directory is {current_directory}")
df = pd.read_csv(f"{current_directory}/raw/data_students.tsv",sep='\t')
print(df)

#Rename the columns to improve machine and human-readability
df = df.rename ({'name':'student_name',"student's age":'student_age','sex of student':'student_sex','location':'student_location','math grade':'grade_math','science':'grade_science','history':'grade_history', 'grade in english':'grade_english'}, axis=1)
print(df)

# Display the number of missing values in each column
print(df.isnull().count())

# Create a new column identifying whether the age column is missing
df['check_age_missing'] = df['student_age'].isnull()

# Replace missing values in the 'age' column with the mean age
df['student_age'] = df['student_age'].fillna(df['student_age'].mean()).round().astype(int)
print(df)

# Convert the 'gender' column to lowercase
df['student_sex']=df['student_sex'].str.lower()
print(df['student_sex'])

# Split the location column into separate columns for city and state
df[['student_location_city','student_location_state']] = df['student_location'].str.split(", ",expand= True)
print(df)

# Save the cleaned data to a new CSV file with an appropriate name
df.to_csv('data_students_cleaned.csv')

current directory is /Users/chenhanlin/Documents/vandy 23 fall/DS 5610 EDA/Assignment/data
    student_id       name  student's age sex of student            location  \
0            1      Alice           23.0         Female         Houston, TX
1            2   Benjamin           31.0           Male         Phoenix, AZ
2            3  Charlotte           30.0        Neither         Chicago, IL
3            4     Daniel           24.0        Unknown          Denver, CO
4            5    Eleanor            NaN           male         Atlanta, GA
5            6      Fiona           27.0         Female           Miami, FL
6            7      Grace           28.0        neither         Seattle, WA
7            8      Henry           21.0        Unknown          Boston, MA
8            9   Isabella           28.0           Male          Austin, TX
9           10       Jack           19.0         female        Portland, OR
10          11  Katherine            NaN        Unknown         Detroit, MI
11          12       Liam           35.0        Neither       Las Vegas, NV
12          13        Mia           27.0        unknown       Charlotte, NC
13          14     Nathan           26.0           Male          Dallas, TX
14          15     Olivia           23.0        Neither   San Francisco, CA
15          16   Penelope           22.0         female     Minneapolis, MN
16          17     Quincy           29.0        Unknown        New York, NY
17          18     Rachel           24.0        neither       Nashville, TN
18          19     Samuel           18.0           Male    Philadelphia, PA
19          20     Taylor            NaN         Female     Los Angeles, CA
20          21        Uma            NaN        Unknown  Salt Lake City, UT
21          22     Victor           20.0        Neither     New Orleans, LA
22          23    William           34.0        unknown    Indianapolis, IN
23          24     Xander           23.0        neither       San Diego, CA
24          25    Yasmine            NaN           male     Kansas City, MO
25          26    Zachary           18.0         Female         Raleigh, NC

    math grade  science  history  grade in english
0           90       60       71                72
1           85       82       74                77
2           69       74       98                94
3           70       80       73                64
4          100       97       64               100
5           94       90       75                93
6           90       90       81                92
7           64       78       60                64
8           86       86       97                83
9           81       94       98                77
10          63       86       94                92
11          75       64       94                72
12          61       83       96                78
13          81       62       78                90
14          77      100       92                81
15          67       95       94                72
16          92       75       90                62
17          94      100       74                81
18          68       70       67                64
19          95       66       90                95
20          86       78       98                80
21          81       77       66                90
22          69       98       99                91
23          85       79       77                92
24          90       70       80                88
25          96       95       78                69
    student_id student_name  student_age student_sex    student_location  \
0            1        Alice         23.0      Female         Houston, TX
1            2     Benjamin         31.0        Male         Phoenix, AZ
2            3    Charlotte         30.0     Neither         Chicago, IL
3            4       Daniel         24.0     Unknown          Denver, CO
4            5      Eleanor          NaN        male         Atlanta, GA
5            6        Fiona         27.0      Female           Miami, FL
6            7        Grace         28.0     neither         Seattle, WA
7            8        Henry         21.0     Unknown          Boston, MA
8            9     Isabella         28.0        Male          Austin, TX
9           10         Jack         19.0      female        Portland, OR
10          11    Katherine          NaN     Unknown         Detroit, MI
11          12         Liam         35.0     Neither       Las Vegas, NV
12          13          Mia         27.0     unknown       Charlotte, NC
13          14       Nathan         26.0        Male          Dallas, TX
14          15       Olivia         23.0     Neither   San Francisco, CA
15          16     Penelope         22.0      female     Minneapolis, MN
16          17       Quincy         29.0     Unknown        New York, NY
17          18       Rachel         24.0     neither       Nashville, TN
18          19       Samuel         18.0        Male    Philadelphia, PA
19          20       Taylor          NaN      Female     Los Angeles, CA
20          21          Uma          NaN     Unknown  Salt Lake City, UT
21          22       Victor         20.0     Neither     New Orleans, LA
22          23      William         34.0     unknown    Indianapolis, IN
23          24       Xander         23.0     neither       San Diego, CA
24          25      Yasmine          NaN        male     Kansas City, MO
25          26      Zachary         18.0      Female         Raleigh, NC

    grade_math  grade_science  grade_history  grade_english
0           90             60             71             72
1           85             82             74             77
2           69             74             98             94
3           70             80             73             64
4          100             97             64            100
5           94             90             75             93
6           90             90             81             92
7           64             78             60             64
8           86             86             97             83
9           81             94             98             77
10          63             86             94             92
11          75             64             94             72
12          61             83             96             78
13          81             62             78             90
14          77            100             92             81
15          67             95             94             72
16          92             75             90             62
17          94            100             74             81
18          68             70             67             64
19          95             66             90             95
20          86             78             98             80
21          81             77             66             90
22          69             98             99             91
23          85             79             77             92
24          90             70             80             88
25          96             95             78             69
student_id          26
student_name        26
student_age         26
student_sex         26
student_location    26
grade_math          26
grade_science       26
grade_history       26
grade_english       26
dtype: int64
    student_id student_name  student_age student_sex    student_location  \
0            1        Alice           23      Female         Houston, TX
1            2     Benjamin           31        Male         Phoenix, AZ
2            3    Charlotte           30     Neither         Chicago, IL
3            4       Daniel           24     Unknown          Denver, CO
4            5      Eleanor           25        male         Atlanta, GA
5            6        Fiona           27      Female           Miami, FL
6            7        Grace           28     neither         Seattle, WA
7            8        Henry           21     Unknown          Boston, MA
8            9     Isabella           28        Male          Austin, TX
9           10         Jack           19      female        Portland, OR
10          11    Katherine           25     Unknown         Detroit, MI
11          12         Liam           35     Neither       Las Vegas, NV
12          13          Mia           27     unknown       Charlotte, NC
13          14       Nathan           26        Male          Dallas, TX
14          15       Olivia           23     Neither   San Francisco, CA
15          16     Penelope           22      female     Minneapolis, MN
16          17       Quincy           29     Unknown        New York, NY
17          18       Rachel           24     neither       Nashville, TN
18          19       Samuel           18        Male    Philadelphia, PA
19          20       Taylor           25      Female     Los Angeles, CA
20          21          Uma           25     Unknown  Salt Lake City, UT
21          22       Victor           20     Neither     New Orleans, LA
22          23      William           34     unknown    Indianapolis, IN
23          24       Xander           23     neither       San Diego, CA
24          25      Yasmine           25        male     Kansas City, MO
25          26      Zachary           18      Female         Raleigh, NC

    grade_math  grade_science  grade_history  grade_english  check_age_missing
0           90             60             71             72              False
1           85             82             74             77              False
2           69             74             98             94              False
3           70             80             73             64              False
4          100             97             64            100               True
5           94             90             75             93              False
6           90             90             81             92              False
7           64             78             60             64              False
8           86             86             97             83              False
9           81             94             98             77              False
10          63             86             94             92               True
11          75             64             94             72              False
12          61             83             96             78              False
13          81             62             78             90              False
14          77            100             92             81              False
15          67             95             94             72              False
16          92             75             90             62              False
17          94            100             74             81              False
18          68             70             67             64              False
19          95             66             90             95               True
20          86             78             98             80               True
21          81             77             66             90              False
22          69             98             99             91              False
23          85             79             77             92              False
24          90             70             80             88               True
25          96             95             78             69              False
0      female
1        male
2     neither
3     unknown
4        male
5      female
6     neither
7     unknown
8        male
9      female
10    unknown
11    neither
12    unknown
13       male
14    neither
15     female
16    unknown
17    neither
18       male
19     female
20    unknown
21    neither
22    unknown
23    neither
24       male
25     female
Name: student_sex, dtype: object
    student_id student_name  student_age student_sex    student_location  \
0            1        Alice           23      female         Houston, TX
1            2     Benjamin           31        male         Phoenix, AZ
2            3    Charlotte           30     neither         Chicago, IL
3            4       Daniel           24     unknown          Denver, CO
4            5      Eleanor           25        male         Atlanta, GA
5            6        Fiona           27      female           Miami, FL
6            7        Grace           28     neither         Seattle, WA
7            8        Henry           21     unknown          Boston, MA
8            9     Isabella           28        male          Austin, TX
9           10         Jack           19      female        Portland, OR
10          11    Katherine           25     unknown         Detroit, MI
11          12         Liam           35     neither       Las Vegas, NV
12          13          Mia           27     unknown       Charlotte, NC
13          14       Nathan           26        male          Dallas, TX
14          15       Olivia           23     neither   San Francisco, CA
15          16     Penelope           22      female     Minneapolis, MN
16          17       Quincy           29     unknown        New York, NY
17          18       Rachel           24     neither       Nashville, TN
18          19       Samuel           18        male    Philadelphia, PA
19          20       Taylor           25      female     Los Angeles, CA
20          21          Uma           25     unknown  Salt Lake City, UT
21          22       Victor           20     neither     New Orleans, LA
22          23      William           34     unknown    Indianapolis, IN
23          24       Xander           23     neither       San Diego, CA
24          25      Yasmine           25        male     Kansas City, MO
25          26      Zachary           18      female         Raleigh, NC

    grade_math  grade_science  grade_history  grade_english  \
0           90             60             71             72
1           85             82             74             77
2           69             74             98             94
3           70             80             73             64
4          100             97             64            100
5           94             90             75             93
6           90             90             81             92
7           64             78             60             64
8           86             86             97             83
9           81             94             98             77
10          63             86             94             92
11          75             64             94             72
12          61             83             96             78
13          81             62             78             90
14          77            100             92             81
15          67             95             94             72
16          92             75             90             62
17          94            100             74             81
18          68             70             67             64
19          95             66             90             95
20          86             78             98             80
21          81             77             66             90
22          69             98             99             91
23          85             79             77             92
24          90             70             80             88
25          96             95             78             69

    check_age_missing student_location_city student_location_state
0               False               Houston                     TX
1               False               Phoenix                     AZ
2               False               Chicago                     IL
3               False                Denver                     CO
4                True               Atlanta                     GA
5               False                 Miami                     FL
6               False               Seattle                     WA
7               False                Boston                     MA
8               False                Austin                     TX
9               False              Portland                     OR
10               True               Detroit                     MI
11              False             Las Vegas                     NV
12              False             Charlotte                     NC
13              False                Dallas                     TX
14              False         San Francisco                     CA
15              False           Minneapolis                     MN
16              False              New York                     NY
17              False             Nashville                     TN
18              False          Philadelphia                     PA
19               True           Los Angeles                     CA
20               True        Salt Lake City                     UT
21              False           New Orleans                     LA
22              False          Indianapolis                     IN
23              False             San Diego                     CA
24               True           Kansas City                     MO
25              False               Raleigh                     NC

4. Generative AI comparison. Use a reliable generative AI like ChatGPT, Claude, Bing, Jupyter AI, etc. to answer the same questions as Section 3. You should alter the prompt given to the AI to maximize the accuracy and efficiency of its output. Paste both your prompt and the generative AI's output below.

In [53]:
# 1 st prompt: You are a great expert in pandas to clean the data. Here is the data. Can you help do the following things? 

# Import "data_students.tsv" into a dataframe

# Rename the columns to improve machine and human-readability

# Display the number of missing values in each column

# Create a new column identifying whether the age column is missing

# Replace missing values in the 'age' column with the mean age

# Convert the 'gender' column to lowercase

# Split the location column into separate columns for city and state

# Save the cleaned data to a new CSV file with an appropriate name

# 2nd prompt: can you show all the codes in one time? 

# output

import pandas as pd

# 1. Import the "data_students.tsv" into a dataframe
df = pd.read_csv("/mnt/data/data_students.tsv", sep="\t")

# 2. Rename the columns to improve machine and human-readability
column_names = {
    "student's age": "age",
    "sex of student": "gender",
    "math grade": "math_grade",
    "science": "science_grade",
    "history": "history_grade",
    "grade in english": "english_grade"
}
df.rename(columns=column_names, inplace=True)

# 3. Display the number of missing values in each column (We displayed this in the output above)
missing_values = df.isnull().sum()

# 4. Create a new column identifying whether the 'age' column is missing
df['age_missing'] = df['age'].isnull()

# 5. Replace missing values in the 'age' column with the mean age
mean_age = df['age'].mean()
df['age'].fillna(mean_age, inplace=True)

# 6. Convert the 'gender' column to lowercase
df['gender'] = df['gender'].str.lower()

# 7. Split the 'location' column into separate columns for city and state
df[['city', 'state']] = df['location'].str.split(',', expand=True)
df.drop(columns='location', inplace=True)

# 8. Save the cleaned data to a new CSV file
output_file_path = "/mnt/data/cleaned_students_data.csv"
df.to_csv(output_file_path, index=False)

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data/data_students.tsv'

5. Generative AI evaluation. Compare the code you produced using static sources to that produced by the generative AI. Write 2-3 paragraphs evaluating the strengths and weaknesses of both approaches. In doing so, you should answer the following questions:
* Having now seen the code produced by Generative AI, how would you have written your code differently?
* Where does Generative AI excel, and where did it fall short?
* What was important in writing your prompt?

Before the advent of Generative AI, I primarily wrote codes on my own and turned to StackOverflow when faced with challenges. Now, if the time is limited, I will ask Generative AI for help; however I will critically evaluate the codes produced by it before using the codes. 

Generative AI has expedited my problem-solving process, offering real-time responses tailored to my queries. However, I still find myself sifting through static resources to validate that the answers correspond accurately to my questions. It's noteworthy that Generative AI tools, like ChatGPT, lack access to the most recent information unless augmented with plugins. Conversely, static online resources benefit from the collective expertise of numerous contributors, ensuring the content remains current. Furthermore, ChatGPT's knowledge is based on data up to 2021. As such, the quality of its responses hinges on this training data, which carries the risk of producing incorrect or less-than-optimal answers. However, answers on static online resources undergo rigorous scrutiny by a variety of users. High acceptance rates signal the credibility of these answers, and the diverse perspectives offered can enhance one's ability to adapt solutions to various scenarios.

When crafting a prompt for ChatGPT, both clarity and context are paramount. ChatGPT struggles with retaining information and managing extended prompts. Hence, it's crucial to pose questions that are concise, explicit, and clear. It's advisable to ask all related questions in one time since the model lacks the capability to remember past interactions over extended periods. Additionally, providing context, such as setting a specific persona for ChatGPT, can significantly improve its comprehension of the query, leading to more efficient and relevant responses.